### ISSUE TITLE
添加数据的时候报错 是什么原因导致的呢

### ISSUE THREAD

**Issue by wotoutengleha** [wechat-miniprogram/recycle-view#59]
Cannot read property 'selectComponent' of null;at api request success callback function
TypeError: Cannot read property 'selectComponent' of null
    at RecycleContext.checkComp (http://127.0.0.1:15512/appservice/miniprogram_npm/miniprogram-recycle-view/index.js:306:29)
    at RecycleContext.appendList (http://127.0.0.1:15512/appservice/miniprogram_npm/miniprogram-recycle-view/index.js:317:10)
    at success (http://127.0.0.1:15512/appservice/pages/BookingBusiness/MyOrder/MyOrder.js:231:33)
    at Object.o.(anonymous function) (WAService.js:1:1116874)
    at Function.<anonymous> (WAService.js:1:438779)
    at WAService.js:1:102889
    at C (WAService.js:1:422326)
    at i.<anonymous> (WAService.js:1:741526)
    at i.emit (WAService.js:1:444906)
    at Rs (WAService.js:1:742134)

**Comment by aimilu** [comment]
同问，解决了吗？
